# These are supported funding model platforms

github: Cabot-bot # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: cabot_bot # Replace with a single Patreon username
ko_fi: cabot # Replace with a single Ko-fi username
